/* Dutch Vocabulary Trainer V2.0 application controller */
const APP_VERSION="2.0.3";
const APP_NAME="Dutch Vocabulary Trainer";
const AppState={version:APP_VERSION,initialized:false,initializing:false,currentView:"home",previousView:null,practiceSession:null,vocabularySelection:null,statistics:null,initializationPromise:null,lastError:null};
const APP_EVENTS={READY:"app-ready",VIEW_CHANGED:"app-view-changed",DATA_CHANGED:"app-data-changed",SELECTION_CHANGED:"app-selection-changed",PRACTICE_STARTED:"app-practice-started",PRACTICE_ANSWERED:"app-practice-answered",PRACTICE_COMPLETED:"app-practice-completed",IMPORT_COMPLETED:"app-import-completed",ERROR:"app-error"};
function dispatchAppEvent(n,d={}){try{window.dispatchEvent(new CustomEvent(n,{detail:{...d,appVersion:APP_VERSION,timestamp:new Date().toISOString()}}))}catch(_) {}}
function handleAppError(e,c="Application"){AppState.lastError={context:c,message:e?.message||String(e),timestamp:new Date().toISOString()};console.error(`${c}:`,e);dispatchAppEvent(APP_EVENTS.ERROR,{error:AppState.lastError});return e}
async function initializeDatabaseLayer(){if(typeof initializeDB==="function")return initializeDB();if(typeof initDatabase==="function")return initDatabase();throw new Error("db.js: no database initialization API is available.")}
async function initializeStorageLayer(){return typeof initializeStorage==="function"?initializeStorage():true}
async function initializeMigrationLayer(){return typeof runMigrations==="function"?runMigrations():true}
async function initializePackLayer(){const p=window.DutchTrainerPacks;if(!p?.ensureDefaultPack)throw new Error("packs.js is unavailable.");return p.ensureDefaultPack()}
function initializeSelectionLayer(){if(typeof getVocabularySelection!=="function")throw new Error("selection.js is unavailable.");return AppState.vocabularySelection=getVocabularySelection()}
async function initializeMasteryLayer(){return typeof recalculateAllMasteryStates==="function"?recalculateAllMasteryStates():{processed:0}}
async function initializeSchedulerLayer(){return typeof initializeScheduler==="function"?initializeScheduler():(window.DutchTrainerScheduler?.initialize?window.DutchTrainerScheduler.initialize():true)}
async function initializeImportLayer(){return typeof initializeImport==="function"?initializeImport():true}
async function initializeDashboardLayer(){return typeof initializeDashboard==="function"?initializeDashboard():true}
async function initializePracticeLayer(){return typeof initializePractice==="function"?initializePractice():true}
async function getApplicationVocabulary(){return typeof getAllWords==="function"?getAllWords():[]}
async function getApplicationSelectedVocabulary(){return typeof getSelectedVocabulary==="function"?getSelectedVocabulary():[]}
function getApplicationSelection(){return typeof getVocabularySelection==="function"?(AppState.vocabularySelection=getVocabularySelection()):AppState.vocabularySelection}
async function changeApplicationSelection(source,packId=null){const calls={all:()=>selectAllVocabulary(),pack:()=>selectVocabularyPack(packId),new:()=>selectNewVocabulary(),weak:()=>selectWeakVocabulary(),due:()=>selectDueVocabulary()};if(calls[source])await calls[source]();AppState.vocabularySelection=getVocabularySelection();dispatchAppEvent(APP_EVENTS.SELECTION_CHANGED,{selection:AppState.vocabularySelection});return AppState.vocabularySelection}
async function refreshApplicationStatistics(){try{const all=await getApplicationVocabulary(),selected=await getApplicationSelectedVocabulary();AppState.statistics={selected,all,updatedAt:new Date().toISOString()};return AppState.statistics}catch(e){handleAppError(e,"Refreshing statistics");return AppState.statistics}}
async function startQuickPractice(options={}){const ps=typeof getPracticeSettings==="function"?getPracticeSettings():{};const type=options.exerciseType??ps.exerciseType??"meaning",count=Number(options.questionCount??ps.questionCount??20),words=await getApplicationSelectedVocabulary();const session=await DutchTrainerPractice.startPractice({mode:"start",exerciseType:type,questionCount:count,vocabulary:words});AppState.practiceSession=session;if(session?.success)navigateTo("practice");return session}
async function startConfiguredPractice(){const type=document.getElementById("exerciseType")?.value||"meaning",custom=document.getElementById("customQuestionCount")?.value,preset=document.querySelector(".countPreset.active")?.dataset.value,ps=typeof getPracticeSettings==="function"?getPracticeSettings():{},count=Math.max(1,Number(custom||preset||ps.questionCount||20)),filter=document.getElementById("vocabularyFilter")?.value||"all",packId=document.getElementById("packSelector")?.value||"all";await changeApplicationSelection(filter,filter==="pack"?packId:null);const words=await getApplicationSelectedVocabulary();const session=await DutchTrainerPractice.startPractice({exerciseType:type,questionCount:count,mode:"full",vocabulary:words});AppState.practiceSession=session;if(session?.success)navigateTo("practice");return session}
async function initializeApplication(){if(AppState.initialized)return AppState;if(AppState.initializationPromise)return AppState.initializationPromise;AppState.initializationPromise=(async()=>{AppState.initializing=true;try{await initializeDatabaseLayer();await initializeStorageLayer();await initializeMigrationLayer();await initializePackLayer();initializeSelectionLayer();await initializeMasteryLayer();await initializeSchedulerLayer();await initializeImportLayer();await initializeDashboardLayer();await initializePracticeLayer();await refreshApplicationStatistics();if(typeof initializeUI==="function")initializeUI();AppState.initialized=true;dispatchAppEvent(APP_EVENTS.READY,{state:AppState});return AppState}catch(e){handleAppError(e,"Application initialization");throw e}finally{AppState.initializing=false}})();try{return await AppState.initializationPromise}finally{AppState.initializationPromise=null}}
window.DutchTrainerApp={version:APP_VERSION,state:AppState,events:APP_EVENTS,initialize:initializeApplication,init:initializeApplication,startQuickPractice,startConfiguredPractice,getVocabulary:getApplicationVocabulary,getSelectedVocabulary:getApplicationSelectedVocabulary,getSelection:getApplicationSelection,changeSelection:changeApplicationSelection,refreshStatistics:refreshApplicationStatistics};
window.addEventListener("DOMContentLoaded",()=>initializeApplication().catch(()=>{}));