/* V2 exercise compatibility layer. Loaded after practice.js and before ui.js. */
(function(){'use strict';
function t(v){return v&&typeof v==='object'?String(v.text??v.label??v.value??v.answer??'').trim():String(v??'').trim()}
function dutch(w){return t(w?.word??w?.term??w?.dutch??w?.text)}function meaning(w){return t(w?.meaning??w?.english??w?.translation??w?.definition)}
function examples(w){const e=w?.examples??w?.exampleSentences??w?.sentences;if(Array.isArray(e))return e.map(t).filter(Boolean);if(typeof e==='string'&&t(e))return[t(e)];return[t(w?.example??w?.sentence)].filter(Boolean)}
function mask(s,w){if(!s)return'';const escaped=dutch(w).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');if(!escaped)return s;const r=new RegExp(escaped,'i');return r.test(s)?s.replace(r,'_____'):s+' _____'}
function opts(vocab,word,type){const source=(vocab||[]).filter(x=>String(x?.id??x?.word)!==String(word?.id??word?.word));const values=[type==='meaning'?meaning(word):dutch(word),...(type==='meaning'?source.map(meaning):source.map(dutch))].filter(Boolean);return [...new Set(values)].slice(0,4).map((x,i)=>({id:i,text:x,correct:i===0}))}
function normalize(q,vocab){if(!q||!q.exercise)return q;const e=q.exercise,type=q.type||e.type||'meaning';e.type=type;e.dutchWord=e.dutchWord||dutch(q.word);e.meaning=e.meaning||meaning(q.word);e.prompt=e.prompt||({meaning:'What does this Dutch word mean?',recall:'What is the Dutch word?',fill:'Complete the sentence.',choose:'Choose the Dutch word that completes the sentence.',production:'Write the Dutch word or expression.'}[type]||'Answer the question.');if(type==='meaning'||type==='choose'){let options=Array.isArray(e.options)?e.options.map((x,i)=>({id:x?.id??i,text:t(x),correct:Boolean(x?.correct||x?.isCorrect)})).filter(x=>x.text):[];if(options.length<4)options=opts(vocab,q.word,type);let correct=options.find(x=>x.correct)?.text;if(!correct)correct=type==='meaning'?meaning(q.word):dutch(q.word);options=options.map(x=>({...x,correct:t(x.text).toLowerCase()===t(correct).toLowerCase()}));if(!options.some(x=>x.correct)&&options[0])options[0].correct=true;e.options=options;e.correctAnswer=options.find(x=>x.correct)?.text||correct;e.inputType='choice'}else if(type==='fill'){const s=t(e.example)||t(e.sentence)||examples(q.word)[0]||`Dit is een voorbeeld met het woord ${dutch(q.word)}.`;e.example=s;e.sentence=mask(s,q.word);e.inputType='text';e.acceptedAnswers=Array.isArray(e.acceptedAnswers)&&e.acceptedAnswers.length?e.acceptedAnswers:[dutch(q.word)]}else{e.inputType='text';e.acceptedAnswers=Array.isArray(e.acceptedAnswers)&&e.acceptedAnswers.length?e.acceptedAnswers:[dutch(q.word)]}q.masteryBefore=Number(q.word?.mastery??q.word?.masteryScore??0)||0;return q}
function install(){const api=window.DutchTrainerPractice;if(!api||api.__exerciseFixInstalled)return;if(typeof api.startPractice!=='function')return;const original=api.startPractice.bind(api);api.startPractice=async function(options={}){const result=await original(options);if(result?.success){const vocab=Array.isArray(options.vocabulary)?options.vocabulary:(result.state?.selectedVocabulary||[]);result.state?.questions?.forEach(q=>normalize(q,vocab));if(result.state?.currentQuestion)normalize(result.state.currentQuestion,vocab);api.state.currentQuestion=result.state.currentQuestion;api.state.currentExercise=result.state.currentQuestion?.exercise;api.state.currentWord=result.state.currentQuestion?.word;result.question=api.state.currentQuestion}return result};api.start=api.startPractice;api.__exerciseFixInstalled=true}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();window.addEventListener('app-ready',install);
})();