/* V2 exercise normalization. Stable contract between vocabulary, practice and UI. */
(function(){
'use strict';
const text=v=>v&&typeof v==='object'?String(v.text??v.label??v.value??v.answer??'').trim():String(v??'').trim();
const dutch=w=>text(w?.word??w?.term??w?.dutch??w?.text);
const meaning=w=>text(w?.meaning??w?.english??w?.translation??w?.definition);
const forms=w=>{const f=w?.forms||{};return [f.base,...(Array.isArray(f.variants)?f.variants:[])].map(text).filter(Boolean)};
const typeOf=q=>String(q?.type??q?.exercise?.type??'meaning').toLowerCase().replace(/[-_ ]/g,'');
const aliases={meaning:'meaning',definition:'meaning',recall:'recall',reverse:'recall',fill:'fill',fillsentence:'fill',sentence:'fill',choose:'choose',chooseword:'choose',multiplechoice:'choose',production:'production',produce:'production',typing:'production'};
function type(q){return aliases[typeOf(q)]||typeOf(q)}
function addExample(out,v){if(Array.isArray(v)){v.forEach(x=>addExample(out,x));return}if(v&&typeof v==='object'){const s=text(v.nl??v.text??v.sentence??v.example??v.context);if(s&&!out.includes(s))out.push(s);return}const s=text(v);if(s&&!out.includes(s))out.push(s)}
function examples(w){const out=[];for(const v of [w?.examples,w?.exampleSentences,w?.sentences,w?.example,w?.exampleSentence,w?.sentence,w?.context])addExample(out,v);for(const e of [...(w?.exercises||[]),...(w?.aiExercises||[]),...(w?.generatedExercises||[])])addExample(out,e?.example??e?.sentence??e?.context);return out}
function mask(sentence,w){const targets=[dutch(w),...forms(w)].filter(Boolean).sort((a,b)=>b.length-a.length);for(const d of targets){const variants=[d,d.replace(/\s+/g,' '),d.replace(/\s+/g,'\\s+')];for(const target of variants){let pattern=target;if(target===d||target===d.replace(/\s+/g,' '))pattern=d.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const esc=target===d.replace(/\s+/g,'\\s+')?target:d.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');try{const re=new RegExp('(^|[^\\p{L}])'+esc+'(?=$|[^\\p{L}])','iu');if(re.test(sentence))return sentence.replace(re,'$1_____')}catch(e){}}}
/* Also handle inflected forms embedded in the example when the pack's target is a base form. */
const base=dutch(w);if(base){const stem=base.replace(/(?:en|s|e)$/i,'');if(stem.length>=4){try{const re=new RegExp('(^|[^\\p{L}])'+stem+'\\p{L}*(?=$|[^\\p{L}])','iu');if(re.test(sentence))return sentence.replace(re,'$1_____')}catch(e){}}}
return sentence+' _____'}
function otherValues(vocab,w,kind){const id=String(w?.id??w?.wordId??w?.word??w?.term??'');return (Array.isArray(vocab)?vocab:[]).filter(x=>String(x?.id??x?.wordId??x?.word??x?.term??'')!==id).flatMap(x=>kind==='meaning'?[meaning(x)]:[dutch(x),...forms(x)]).filter(Boolean)}
function options(vocab,w,kind,current){const correct=kind==='meaning'?meaning(w):dutch(w),vals=[];const add=v=>{const s=text(v);if(s&&!vals.some(x=>x.toLowerCase()===s.toLowerCase()))vals.push(s)};add(correct);(Array.isArray(current)?current:[]).forEach(add);otherValues(vocab,w,kind).forEach(add);return vals.slice(0,4).map((s,i)=>({id:i,text:s,correct:s.toLowerCase()===correct.toLowerCase()}))}
function accepted(w,e){const out=[];const add=v=>{const s=text(v);if(s&&!out.some(x=>x.toLowerCase()===s.toLowerCase()))out.push(s)};[e?.acceptedAnswers,e?.answer,e?.correctAnswer,dutch(w),...forms(w)].forEach(v=>Array.isArray(v)?v.forEach(add):add(v));return out}
function normalize(q,vocab){if(!q||!q.word)return q;const e=q.exercise||(q.exercise={}),t=type(q);q.type=t;e.type=t;e.dutchWord=dutch(q.word);e.meaning=meaning(q.word);e.prompt=e.prompt||({meaning:'What does this Dutch word mean?',recall:'What is the Dutch word?',fill:'Complete the sentence.',choose:'Choose the Dutch word that completes the sentence.',production:'Write the Dutch word or expression.'}[t]||'Answer the question.');const sentence=examples(q.word)[0]||'';
if(t==='meaning'||t==='choose'){e.options=options(vocab,q.word,t,e.options);e.correctAnswer=(e.options.find(x=>x.correct)||{}).text||(t==='meaning'?meaning(q.word):dutch(q.word));e.acceptedAnswers=[e.correctAnswer];e.inputType='choice';if(t==='choose'){e.example=sentence;e.sentence=sentence?mask(sentence,q.word):`Complete the sentence with the word "${dutch(q.word)}".`}}
else if(t==='fill'){e.example=sentence;e.sentence=sentence?mask(sentence,q.word):`Complete the sentence with the word "${dutch(q.word)}".`;e.correctAnswer=dutch(q.word);e.acceptedAnswers=accepted(q.word,e);e.inputType='text'}
else{e.correctAnswer=dutch(q.word);e.acceptedAnswers=accepted(q.word,e);e.inputType='text'}
q.acceptedAnswers=accepted(q.word,e);q.masteryBefore=Number(q.word?.mastery??q.word?.masteryScore??0)||0;return q}
function norm(v){return String(v??'').trim().toLocaleLowerCase('nl-NL').replace(/\s+/g,' ')}
function lev(a,b){a=norm(a);b=norm(b);const d=Array.from({length:a.length+1},(_,i)=>i);for(let j=1;j<=b.length;j++){let prev=d[0];d[0]=j;for(let i=1;i<=a.length;i++){const cur=d[i];d[i]=Math.min(d[i]+1,d[i-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=cur}}return d[a.length]}
function typoLimit(length){if(length<=5)return 1;if(length<=10)return 2;if(length<=15)return 3;if(length<=20)return 4;return 5}
function closest(value,answers){let best=null;for(const a of answers){const d=lev(value,a);if(!best||d<best.distance)best={answer:a,distance:d}}return best}
function install(){const api=window.DutchTrainerPractice;if(!api||api.__exerciseFixInstalled)return;const start=api.startPractice.bind(api),next=api.nextQuestion.bind(api),check=api.checkAnswer.bind(api);api.startPractice=async(o={})=>{const r=await start(o);if(r?.success){const v=r.state.selectedVocabulary||o.vocabulary||[];r.state.questions.forEach(q=>normalize(q,v));api.state.currentQuestion=r.state.questions[0];api.state.currentExercise=api.state.currentQuestion?.exercise;api.state.currentWord=api.state.currentQuestion?.word;r.question=api.state.currentQuestion;window.__DutchTrainerLastPractice={exerciseType:r.state.exerciseType,questionCount:r.state.questionCount,mode:r.state.mode,vocabulary:r.state.selectedVocabulary}}return r};api.nextQuestion=()=>{const r=next();if(r?.question){normalize(r.question,api.state.selectedVocabulary||window.__DutchTrainerLastPractice?.vocabulary||[]);api.state.currentQuestion=r.question;api.state.currentExercise=r.question.exercise;api.state.currentWord=r.question.word}return r};api.checkAnswer=async answer=>{const q=api.state.currentQuestion;if(q)normalize(q,api.state.selectedVocabulary||window.__DutchTrainerLastPractice?.vocabulary||[]);const expected=q?.exercise?.correctAnswer||dutch(q?.word),actual=text(answer),answers=q?.acceptedAnswers?.length?q.acceptedAnswers:accepted(q?.word,q?.exercise),match=closest(actual,answers.length?answers:[expected]);const exact=!!match&&match.distance===0;const limit=match?typoLimit(Math.max(match.answer.length,actual.length)):0;const almost=!exact&&!!match&&['recall','fill','production'].includes(q?.type)&&match.distance<=limit;if(q)q.__almost=almost;q.__closestAnswer=match?.answer||expected;const r=exact||almost?await check(match.answer):await check(answer);if(r?.success){r.correct=exact;r.feedback=r.feedback||{};r.feedback.correct=exact;r.feedback.almost=almost;r.feedback.message=exact?'Correct!':(almost?'Not quite.':'Not correct.');r.feedback.correctAnswer=match?.answer||expected;r.feedback.closestAnswer=match?.answer||expected;r.feedback.spellingDistance=match?.distance??null;r.feedback.spellingLimit=limit}return r};api.start=api.startPractice;api.__exerciseFixInstalled=true;window.normalizePracticeQuestion=normalize;window.getPracticeSpellingResult=(value,answers)=>{const m=closest(value,answers||[]);if(!m)return null;return {exact:m.distance===0,almost:m.distance>0&&m.distance<=typoLimit(Math.max(m.answer.length,String(value||'').length)),distance:m.distance,limit:typoLimit(Math.max(m.answer.length,String(value||'').length)),answer:m.answer}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();window.addEventListener('app-ready',install);
})();