/* V2 exercise compatibility layer. Loaded after practice.js and before ui.js. */
(function(){
'use strict';
function t(v){return v&&typeof v==='object'?String(v.text??v.label??v.value??v.answer??'').trim():String(v??'').trim()}
function dutch(w){return t(w?.word??w?.term??w?.dutch??w?.text)}
function meaning(w){return t(w?.meaning??w?.english??w?.translation??w?.definition)}
function wordExamples(w){const e=w?.examples??w?.exampleSentences??w?.sentences;if(Array.isArray(e))return e.map(t).filter(Boolean);if(typeof e==='string'&&t(e))return[t(e)];return[t(w?.example??w?.exampleSentence??w?.sentence??w?.context)].filter(Boolean)}
function exerciseExample(w,type){const list=[...(Array.isArray(w?.exercises)?w.exercises:[]),...(Array.isArray(w?.aiExercises)?w.aiExercises:[]),...(Array.isArray(w?.generatedExercises)?w.generatedExercises:[])];const hit=list.find(x=>String(x?.type??x?.exerciseType??'').toLowerCase().replace(/[-_ ]/g,'')===type);return t(hit?.example??hit?.sentence??hit?.context)}
function mask(s,w){if(!s)return'';const d=dutch(w);if(!d)return s+' _____';const escaped=d.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const r=new RegExp(escaped,'iu');return r.test(s)?s.replace(r,'_____'):s+' _____'}
function sourceValues(vocab,word,type){const same=(vocab||[]).filter(x=>String(x?.id??x?.word??x?.term)!==String(word?.id??word?.word??word?.term));const getter=type==='meaning'?meaning:dutch;return same.map(getter).filter(Boolean)}
function makeOptions(vocab,word,type,current){const correct=type==='meaning'?meaning(word):dutch(word);const existing=(current||[]).map(x=>t(x)).filter(Boolean);const candidates=[...existing,...sourceValues(vocab,word,type)];const unique=[];for(const x of [correct,...candidates]){if(!x)continue;if(!unique.some(y=>y.toLowerCase()===x.toLowerCase()))unique.push(x);if(unique.length===4)break}return unique.map((x,i)=>({id:i,text:x,correct:x.toLowerCase()===correct.toLowerCase()}))}
function normalize(q,vocab){if(!q||!q.exercise)return q;const e=q.exercise,type=String(q.type||e.type||'meaning').toLowerCase();e.type=type;e.dutchWord=e.dutchWord||dutch(q.word);e.meaning=e.meaning||meaning(q.word);e.prompt=e.prompt||({meaning:'What does this Dutch word mean?',recall:'What is the Dutch word?',fill:'Complete the sentence.',choose:'Choose the Dutch word that completes the sentence.',production:'Write the Dutch word or expression.'}[type]||'Answer the question.');if(type==='meaning'||type==='choose'){e.options=makeOptions(vocab,q.word,type,e.options);e.correctAnswer=e.options.find(x=>x.correct)?.text||(type==='meaning'?meaning(q.word):dutch(q.word));e.inputType='choice'}else if(type==='fill'){const sentence=t(e.example)||t(e.sentence)||exerciseExample(q.word,'fill')||wordExamples(q.word)[0]||`Ik gebruik het woord ${dutch(q.word)} vandaag.`;e.example=sentence;e.sentence=mask(sentence,q.word);e.correctAnswer=dutch(q.word);e.acceptedAnswers=[dutch(q.word)];e.inputType='text'}else{e.inputType='text';e.correctAnswer=dutch(q.word);e.acceptedAnswers=[dutch(q.word)]}q.masteryBefore=Number(q.word?.mastery??q.word?.masteryScore??0)||0;return q}
function normalizeText(v){return String(v??'').trim().toLocaleLowerCase('nl-NL').replace(/\s+/g,' ')}
function distance(a,b){if(typeof levenshteinDistance==='function')return levenshteinDistance(normalizeText(a),normalizeText(b));a=normalizeText(a);b=normalizeText(b);const m=Array.from({length:a.length+1},(_,i)=>i);for(let j=1;j<=b.length;j++){let prev=m[0];m[0]=j;for(let i=1;i<=a.length;i++){const cur=m[i];m[i]=Math.min(m[i]+1,m[i-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=cur}}return m[a.length]}
function vocabularyFor(options,state){return Array.isArray(options?.vocabulary)?options.vocabulary:(state?.selectedVocabulary||[])}
function install(){const api=window.DutchTrainerPractice;if(!api||api.__exerciseFixInstalled)return;if(typeof api.startPractice!=='function')return;const originalStart=api.startPractice.bind(api),originalNext=api.nextQuestion.bind(api),originalCheck=api.checkAnswer.bind(api);api.startPractice=async function(options={}){const result=await originalStart(options);if(result?.success){const vocab=vocabularyFor(options,result.state);result.state?.questions?.forEach(q=>normalize(q,vocab));if(result.state?.currentQuestion)normalize(result.state.currentQuestion,vocab);api.state.currentQuestion=result.state.currentQuestion;api.state.currentExercise=result.state.currentQuestion?.exercise;api.state.currentWord=result.state.currentQuestion?.word;result.question=api.state.currentQuestion;window.__DutchTrainerLastPractice={exerciseType:result.state.exerciseType,questionCount:result.state.questionCount,mode:result.state.mode,vocabulary:result.state.selectedVocabulary}}return result};api.nextQuestion=function(){const result=originalNext();if(result?.question){const vocab=api.state.selectedVocabulary||window.__DutchTrainerLastPractice?.vocabulary||[];normalize(result.question,vocab);api.state.currentQuestion=result.question;api.state.currentExercise=result.question.exercise;api.state.currentWord=result.question.word}return result};api.checkAnswer=async function(answer){const q=api.state.currentQuestion;if(q)normalize(q,api.state.selectedVocabulary||window.__DutchTrainerLastPractice?.vocabulary||[]);const result=await originalCheck(answer);if(result?.success&&!result.correct&&q&&['recall','fill','production'].includes(q.type)){const expected=dutch(q.word),actual=t(answer);const d=distance(actual,expected);const max=Math.max(expected.length,actual.length);const almost=d===1||(d===2&&max>=8);if(almost){result.feedback=result.feedback||{};result.feedback.almost=true;result.feedback.message='Not quite.'}}return result};api.start=api.startPractice;api.__exerciseFixInstalled=true;window.normalizePracticeQuestion=(q,v)=>normalize(q,v)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();window.addEventListener('app-ready',install);
})();