/* =========================================================
   DUTCH VOCABULARY TRAINER V2.0 - JSON WORD PACK IMPORT
========================================================= */
const IMPORT_VERSION="2.0.0";
const IMPORT_LIMITS={maxFileSize:10*1024*1024,maxWords:10000,maxExercisesPerWord:100};
const ImportState={initialized:false,importing:false,lastResult:null,lastError:null};
function normalizeImportText(v){return v==null?"":String(v).trim()}
function normalizeImportId(v){const s=normalizeImportText(v);return s||null}
function generateImportId(prefix="id"){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,10)}`}
function importSlugify(v){return normalizeImportText(v).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
function getPackMeta(data){return data?.metadata||data?.pack||data?.wordPack||{}}
function getImportedPackName(data){const m=getPackMeta(data);return normalizeImportText(m.name??data.name??data.packName??data.title??"Imported Word Pack")}
function getImportedPackDescription(data){const m=getPackMeta(data);return normalizeImportText(m.description??data.description??"")}
function extractImportedWords(data){if(Array.isArray(data))return data;const c=[data?.words,data?.vocabulary,data?.terms,data?.entries,data?.items,data?.data?.words,data?.data?.vocabulary];return c.find(Array.isArray)||[]}
function validateImportedData(data){const words=extractImportedWords(data),errors=[];if(!data||typeof data!=="object")errors.push("The imported file must contain JSON data.");if(!words.length)errors.push("No vocabulary words were found in the imported file.");if(words.length>IMPORT_LIMITS.maxWords)errors.push(`The Word Pack contains ${words.length} words. Maximum is ${IMPORT_LIMITS.maxWords}.`);return{valid:!errors.length,errors,wordCount:words.length}}
function normalizeImportedExercise(ex,word){if(!ex||typeof ex!=="object")return null;return{...ex,type:normalizeImportedExerciseType(ex.type??ex.exerciseType??"meaning"),wordId:ex.wordId??word.id}}
function normalizeImportedExerciseType(t){const v=normalizeImportText(t).toLowerCase().replace(/[\s_-]+/g,"");return{meaning:"meaning",definition:"meaning",recall:"recall",recognition:"recall",fillsentence:"fill",sentence:"fill",fill:"fill",chooseword:"choose",multiplechoice:"choose",choose:"choose",production:"production",translate:"production",translation:"production"}[v]??"meaning"}
function normalizeImportedWord(raw,packId){if(!raw||typeof raw!=="object")return null;const word={...raw};word.id=normalizeImportId(raw.id??raw.wordId??raw.termId)||generateImportId("word");word.word=normalizeImportText(raw.word??raw.term??raw.dutch??raw.text);word.term=normalizeImportText(raw.term??word.word);word.meaning=normalizeImportText(raw.meaning??raw.definition??raw.translation??raw.english??"");if(raw.dutch!==undefined)word.dutch=raw.dutch;if(raw.english!==undefined)word.english=raw.english;if(raw.level!==undefined)word.level=raw.level;if(raw.forms!==undefined)word.forms=raw.forms;if(raw.examples!==undefined)word.examples=raw.examples;word.packId=packId;word.exercises=(raw.exercises??raw.aiExercises??raw.generatedExercises??[]).slice(0,IMPORT_LIMITS.maxExercisesPerWord).map(e=>normalizeImportedExercise(e,raw)).filter(Boolean);word.mastery=Number.isFinite(Number(raw.mastery))?Math.max(0,Math.min(100,Number(raw.mastery))):0;if(raw.stats&&typeof raw.stats==="object")word.stats={...raw.stats,byExerciseType:{...(raw.stats.byExerciseType||{})}};word.history=Array.isArray(raw.history)?[...raw.history]:Array.isArray(raw.answerHistory)?[...raw.answerHistory]:[];word.dueAt=raw.dueAt??raw.nextReview??raw.nextReviewAt;word.nextReview=raw.nextReview??raw.nextReviewAt??raw.dueAt??Date.now();word.isNew=raw.isNew??true;word.createdAt=raw.createdAt??new Date().toISOString();word.updatedAt=new Date().toISOString();word.source=raw.source??"import";word.imported=true;word.importedAt=new Date().toISOString();return word}
function createImportedPack(data){const m=getPackMeta(data),name=getImportedPackName(data),supplied=normalizeImportId(m.packId??data.packId??m.id??data.pack?.id),packId=supplied||`pack_${importSlugify(name)||"import"}_${Date.now().toString(36)}`,words=extractImportedWords(data),now=new Date().toISOString();return{packId,id:packId,name,description:getImportedPackDescription(data),author:m.author??data.author??"",version:m.version??data.packVersion??data.version??"1.0",source:m.source??data.source??"",language:m.language??data.language??"nl",targetLanguage:m.targetLanguage??data.targetLanguage??"en",wordCount:words.length,imported:true,importedAt:now,createdAt:m.createdAt??now,updatedAt:now,metadata:{...m}}}
async function saveImportedPack(pack){return savePack(pack)}
async function getExistingImportedWord(id){if(!id)return null;return typeof getWord==="function"?getWord(id):null}
async function findDuplicateImportedWord(word,packId){const words=await getAllWords(),n=normalizeImportText(word.word).toLowerCase();return words.find(w=>String(w.packId??"")===String(packId)&&normalizeImportText(w.word??w.term).toLowerCase()===n)||null}
function mergeImportedWord(existing,imported){if(!existing)return imported;return{...existing,...imported,id:existing.id,packId:imported.packId,mastery:existing.mastery??imported.mastery,stats:existing.stats??imported.stats,history:existing.history?.length?existing.history:imported.history,exercises:[...(existing.exercises||[]),...(imported.exercises||[])],dueAt:existing.dueAt??imported.dueAt,nextReview:existing.nextReview??imported.nextReview,updatedAt:new Date().toISOString()}}
async function importWordPack(data,options={}){if(ImportState.importing)throw Error("An import is already in progress.");ImportState.importing=true;try{const v=validateImportedData(data);if(!v.valid)throw Error(v.errors.join(" "));await (typeof initializeDB==="function"?initializeDB():window.DutchTrainerDatabaseReady);const pack=createImportedPack(data);await saveImportedPack(pack);let added=0,updated=0,skipped=0;const words=[];for(const raw of extractImportedWords(data)){const w=normalizeImportedWord(raw,pack.packId);if(!w?.word){skipped++;continue}let existing=await getExistingImportedWord(w.id);if(!existing)existing=await findDuplicateImportedWord(w,pack.packId);const final=existing?mergeImportedWord(existing,w):w;await saveWord(final);words.push(final);existing?updated++:added++}pack.wordCount=words.length;pack.updatedAt=new Date().toISOString();await saveImportedPack(pack);if(options.selectImportedPack!==false&&typeof selectVocabularyPack==="function")await selectVocabularyPack(pack.packId);const result={success:true,pack,packId:pack.packId,words,added,updated,skipped,total:words.length,importedAt:new Date().toISOString()};ImportState.lastResult=result;return result}catch(e){ImportState.lastError=e;throw e}finally{ImportState.importing=false}}
async function importWordPackFromText(text,options={}){let data;try{data=JSON.parse(text)}catch(e){throw Error("The imported file is not valid JSON.")}return importWordPack(data,options)}
async function importWordPackFile(file,options={}){if(!file)throw Error("No file was selected.");if(file.size>IMPORT_LIMITS.maxFileSize)throw Error("The selected file is too large. Maximum size is 10 MB.");if(!file.name.toLowerCase().endsWith(".json"))throw Error("Please select a JSON Word Pack file.");return importWordPackFromText(await file.text(),options)}
async function handleWordPackFileInput(e,options={}){const f=e?.target?.files?.[0];if(!f)return null;try{return await importWordPackFile(f,options)}finally{e.target.value=""}}
function buildImportPreview(data){const v=validateImportedData(data);if(!v.valid)return{valid:false,errors:v.errors};const words=extractImportedWords(data);return{valid:true,packName:getImportedPackName(data),wordCount:words.length,exerciseCount:words.reduce((n,w)=>n+(Array.isArray(w.exercises)?w.exercises.length:0),0),description:getImportedPackDescription(data),version:getPackMeta(data).version??data.version??"1.0"}}
function initializeImport(){ImportState.initialized=true;return true}
window.DutchTrainerImport={version:IMPORT_VERSION,state:ImportState,importWordPack,importFromText:importWordPackFromText,importFile:importWordPackFile,preview:buildImportPreview,selectPack:async id=>typeof selectVocabularyPack==="function"?selectVocabularyPack(id):false,validate:validateImportedData};window.importWordPack=importWordPack;window.importWordPackFile=importWordPackFile;window.handleWordPackFileInput=handleWordPackFileInput;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initializeImport,{once:true});else initializeImport();
