'use strict';
const DutchTrainer=window.DutchTrainer||(window.DutchTrainer={});
const DEFAULTS=Object.freeze({exerciseType:'meaning',questionCount:20,mode:'start'});
const TYPES=Object.freeze(['meaning','recall','fill','choose','production']);
let state={active:false,completed:false,mode:DEFAULTS.mode,exerciseType:DEFAULTS.exerciseType,questionCount:0,currentIndex:0,questions:[],correctCount:0,answerCount:0,startedAt:null,finishedAt:null,selectedVocabulary:[],selection:{source:'all',packId:null}};
const listeners=new Map();
function normalizeType(v){const t=String(v||DEFAULTS.exerciseType).trim().toLowerCase();const a={'fill-sentence':'fill','choose-word':'choose','multiple-choice':'meaning'};const n=a[t]||t;return TYPES.includes(n)||n==='mixed'?n:DEFAULTS.exerciseType;}
function normalizeCount(v){const n=Number(v);return Math.max(1,Math.min(500,Number.isFinite(n)?Math.floor(n):DEFAULTS.questionCount));}
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
function wordId(w){return String(w?.id??w?.wordId??w?.dutch??w?.word??'');}
function emit(e,p){(listeners.get(e)||[]).forEach(fn=>{try{fn(p);}catch(err){console.warn(err);}});}
function getState(){return clone(state);}
function answerValue(a){return a&&typeof a==='object'?String(a.value??a.answer??a.text??a.label??'').trim():String(a??'').trim();}
async function getVocabulary(options={}){if(Array.isArray(options.vocabulary))return{words:options.vocabulary,selection:{source:'all',packId:null}};if(!DutchTrainer.vocabulary?.getSelected)throw new Error('DutchTrainer.vocabulary.getSelected is unavailable.');return{words:await DutchTrainer.vocabulary.getSelected(),selection:DutchTrainer.vocabulary.getSelection?.()||{source:'all',packId:null}};}
function buildQuestion(word,type,vocabulary,optionVocabulary=vocabulary){const exercise=DutchTrainer.exercises?.create?.(word,type,optionVocabulary);if(!exercise)throw new Error(`Exercise '${type}' is unavailable.`);return{id:`${wordId(word)}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,wordId:wordId(word),type,word:clone(word),exercise:clone(exercise),answered:false,answer:null,result:null,feedback:null};}
function shuffle(v){const r=[...v];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;}
function buildQuestions(words,count,type,optionVocabulary=words){const pool=shuffle(words);return Array.from({length:count},(_,i)=>buildQuestion(pool[i%pool.length],type==='mixed'?TYPES[i%TYPES.length]:type,words,optionVocabulary));}
function checkAnswerValue(question,answer){const value=answerValue(answer);if(!value)return{correct:false,almost:false,empty:true,score:0};const ex=DutchTrainer.exercises?.get?.(question.type);if(!ex?.check)return{correct:false,almost:false,empty:false,score:0};const raw=ex.check({...question.exercise,word:question.word},value);const result=typeof raw==='object'?raw:{correct:Boolean(raw),almost:false};return{correct:Boolean(result.correct),almost:Boolean(result.almost),empty:false,score:result.correct?1:0,expected:question.exercise.correctAnswer||question.exercise.answer||''};}
async function start(options={}){const type=normalizeType(options.exerciseType),questionCount=normalizeCount(options.questionCount),resolved=await getVocabulary(options);if(!resolved.words.length)return{success:false,reason:'no-vocabulary',state:getState()};let optionVocabulary=resolved.words;if((type==='meaning'||type==='choose')&&resolved.words.length<4&&DutchTrainer.vocabulary?.getAll)optionVocabulary=await DutchTrainer.vocabulary.getAll();const questions=buildQuestions(resolved.words,questionCount,type,resolved.words.length<4?optionVocabulary:resolved.words);state={active:true,completed:false,mode:options.mode||DEFAULTS.mode,exerciseType:type,questionCount:questions.length,currentIndex:0,questions,correctCount:0,answerCount:0,startedAt:new Date().toISOString(),finishedAt:null,selectedVocabulary:clone(resolved.words),selection:clone(resolved.selection)};emit('start',getState());return{success:true,state:getState(),question:clone(state.questions[0])};}
async function answer(answer){if(!state.active||state.completed)throw new Error('No active practice session.');const q=state.questions[state.currentIndex];if(q.answered)return{success:false,reason:'already-answered',state:getState(),question:clone(q)};const value=answerValue(answer),check=checkAnswerValue(q,value);if(check.empty)return{success:false,reason:'empty-answer',state:getState(),question:clone(q)};let masteryResult=null;if(DutchTrainer.mastery?.recordAnswer)masteryResult=await DutchTrainer.mastery.recordAnswer(q.word,{correct:check.correct,almost:check.almost,userAnswer:value,expectedAnswer:check.expected,exerciseType:q.type},q.exercise);q.answered=true;q.answer=value;q.result=check.correct?'correct':check.almost?'almost':'incorrect';q.feedback={...check,mastery:Number(masteryResult?.masteryAfter??q.word.mastery??0)};state.answerCount++;if(check.correct)state.correctCount++;emit('answer',{question:clone(q),result:clone(masteryResult||check),state:getState()});return{success:true,correct:check.correct,almost:check.almost,feedback:clone(q.feedback),mastery:Number(masteryResult?.masteryAfter??q.feedback.mastery??0),historyEntry:masteryResult?.historyEntry,state:getState(),question:clone(q)};}
async function finish(){if(!state.active)return{success:false,reason:'no-active-session',state:getState()};if(state.completed)return{success:true,state:getState()};state.completed=true;state.active=false;state.finishedAt=new Date().toISOString();const results=state.questions.filter(q=>q.answered).map(q=>({wordId:q.wordId,dutch:q.word?.dutch||q.word?.word||'',exerciseType:q.type,correct:q.result==='correct',almost:q.result==='almost',mastery:Number(q.feedback?.mastery)||Number(q.word?.mastery)||0}));const masteryValues=results.map(r=>r.mastery).filter(Number.isFinite);const session={id:`session-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,startedAt:state.startedAt,finishedAt:state.finishedAt,exerciseType:state.exerciseType,mode:state.mode,questionCount:state.questionCount,answerCount:state.answerCount,correctCount:state.correctCount,mastery:masteryValues.length?Math.round(masteryValues.reduce((a,b)=>a+b,0)/masteryValues.length):0,results,selectedVocabulary:clone(state.selectedVocabulary),selection:clone(state.selection)};if(DutchTrainer.history?.saveSession)await DutchTrainer.history.saveSession(session);state.session=session;emit('finish',{session:clone(session),state:getState()});return{success:true,session:clone(session),state:getState()};}
async function next(){if(!state.active)return{completed:true,state:getState()};if(!state.questions[state.currentIndex]?.answered)throw new Error('Answer the current question first.');if(state.currentIndex>=state.questions.length-1)return{completed:true,...(await finish())};state.currentIndex++;emit('next',getState());return{completed:false,state:getState(),question:clone(state.questions[state.currentIndex])};}
function reset(){state={...state,active:false,completed:false,currentIndex:0,questions:[],correctCount:0,answerCount:0,startedAt:null,finishedAt:null,selectedVocabulary:[],session:undefined};emit('reset',getState());return getState();}
function on(event,handler){if(!listeners.has(event))listeners.set(event,new Set());listeners.get(event).add(handler);return()=>listeners.get(event)?.delete(handler);}
DutchTrainer.practice=Object.freeze({start,answer,next,finish,reset,getState,on});window.DutchTrainerPractice=DutchTrainer.practice;window.getPracticeState=getState;
