/* Dutch Vocabulary Trainer V2.0 UI */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const text=v=>v&&typeof v==='object'?String(v.text??v.label??v.value??v.answer??'').trim():String(v??'').trim();
async function setting(k,f){try{return await getSetting(k,f)}catch(_){return f}}
async function saveSetting(k,v){try{return await setSetting(k,v)}catch(e){console.warn(e);return false}}
const viewMap={home:'homeScreen',dashboard:'dashboardScreen',packs:'packsScreen',settings:'settingsScreen',practice:'practiceScreen',complete:'completeScreen',history:'historyScreen'};
function nav(name,push=true){const target=viewMap[name]||name;document.querySelectorAll('.screen').forEach(e=>e.classList.remove('active'));$(target)?.classList.add('active');if(push&&name!=='home'){try{history.pushState({view:name},'',`#${name}`)}catch(_){}}if(name==='home'&&push){try{history.pushState({view:'home'},'',location.pathname+location.search)}catch(_){}}if(name==='dashboard')window.DutchTrainerDashboard?.render?.();if(name==='packs')loadPacks();if(name==='settings')loadSettings();if(name==='history')renderHistory()}
function goBack(){nav('home')}
window.addEventListener('popstate',e=>nav(e.state?.view||'home',false));
async function loadSettings(){$('settingsExerciseType').value=await setting('practice.exerciseType','meaning');$('settingsQuestionCount').value=await setting('practice.questionCount',20);$('settingsTheme').value=await setting('ui.theme','system');applyTheme($('settingsTheme').value)}
function applyTheme(t){document.documentElement.dataset.theme=t||'system'}
async function saveSettings(){const type=$('settingsExerciseType').value;const n=Math.max(1,Math.min(500,Number($('settingsQuestionCount').value)||20));await saveSetting('practice.exerciseType',type);await saveSetting('practice.questionCount',n);await saveSetting('ui.theme',$('settingsTheme').value);$('settingsStatus').textContent=`Saved: ${type}, ${n} questions. Start Practice will use these defaults.`;applyTheme($('settingsTheme').value);await populateDefaults()}
async function loadPacks(){if(!window.DutchTrainerPacks)return;try{const ps=await DutchTrainerPacks.getAllPacks();const list=$('packsList'),sel=$('packSelector');if(sel){sel.innerHTML='<option value="all">All Packs</option>';ps.forEach(p=>{const o=document.createElement('option');o.value=p.packId;o.textContent=p.name;sel.appendChild(o)})}if(list){list.innerHTML='';if(!ps.length){list.textContent='No vocabulary packs installed.'}else ps.forEach(p=>{const d=document.createElement('div');d.className='card';const h=document.createElement('strong');h.textContent=p.name;const n=document.createElement('p');n.textContent=`${Number(p.wordCount||0)} words`;d.append(h,n);list.appendChild(d)})}}catch(e){console.error(e);if($('packsList'))$('packsList').textContent='Could not load Word Packs: '+e.message}}
async function importPack(){const f=$('packFileInput')?.files?.[0];if(!f){$('importStatus').textContent='Please choose a JSON Word Pack first.';return}try{const r=await DutchTrainerImport.importFile(f,{selectImportedPack:true});$('importStatus').textContent=`Imported ${r.pack.name}: ${r.added} new, ${r.updated} updated, ${r.skipped} skipped.`;$('packFileInput').value='';$('packNameInput').value='';await loadPacks();if(r.pack?.packId&&$('packSelector'))$('packSelector').value=r.pack.packId}catch(e){console.error(e);$('importStatus').textContent='Import failed: '+e.message}}
async function populateDefaults(){const t=await setting('practice.exerciseType','meaning'),n=Number(await setting('practice.questionCount',20));if($('exerciseType'))$('exerciseType').value=t;if($('customQuestionCount'))$('customQuestionCount').value='';document.querySelectorAll('.countPreset').forEach(b=>b.classList.toggle('active',Number(b.dataset.value)===n))}
function renderMastery(value,label){$('masteryArea')?.remove();const d=document.createElement('div');d.id='masteryArea';d.className='mastery-display';d.textContent=`Mastery ${label}: ${Math.round(Number(value)||0)}%`;$('questionCard')?.insertBefore(d,$('answerArea'))}
function normalizeQuestion(qn){const state=DutchTrainerPractice.getState();const vocab=state.selectedVocabulary||window.__DutchTrainerLastPractice?.vocabulary||[];return window.normalizePracticeQuestion?window.normalizePracticeQuestion(qn,vocab):qn}
function renderQuestion(qn){if(!qn)return;qn=normalizeQuestion(qn)||qn;const ex=qn.exercise||{},type=String(qn.type||ex.type||'meaning').toLowerCase();$('exerciseBadge').textContent=ex.label||({meaning:'Meaning',recall:'Recall',fill:'Fill Sentence',choose:'Choose Word',production:'Production'}[type]||type);const prompts={meaning:'What does this Dutch word mean?',recall:'What is the Dutch word?',fill:'Complete the sentence.',choose:'Choose the Dutch word that completes the sentence.',production:'Write the Dutch word or expression.'};$('questionPrompt').textContent=ex.prompt||ex.question||prompts[type]||'Answer the question.';const c=$('questionContext');c.textContent=type==='meaning'?(ex.dutchWord||qn.word?.word||''):type==='recall'?(ex.meaning||qn.word?.meaning||''):(ex.sentence||ex.example||ex.context||'');const area=$('answerArea');area.innerHTML='';if(type==='meaning'||type==='choose'||ex.inputType==='choice'){(Array.isArray(ex.options)?ex.options:[]).forEach((o,i)=>{const s=text(o);if(!s)return;const l=document.createElement('label');l.className='practice-option';const r=document.createElement('input');r.type='radio';r.name='practiceChoice';r.value=s;r.dataset.optionIndex=i;l.append(r,document.createTextNode(' '+s));area.appendChild(l)});if(!area.children.length){const p=document.createElement('p');p.textContent='No choices available.';area.appendChild(p)}}else{const i=document.createElement('input');i.id='answerInput';i.type='text';i.autocomplete='off';i.placeholder=type==='fill'?'Type the missing word':'Type your answer';area.appendChild(i);setTimeout(()=>i.focus(),0)}$('feedbackArea').innerHTML='';$('checkBtn').classList.remove('hidden');$('nextBtn').classList.add('hidden');const s=DutchTrainerPractice.getState(),total=s.questions?.length||0;$('sessionCounter').textContent=`${s.currentIndex+1}/${total}`;if($('sessionProgressFill'))$('sessionProgressFill').style.width=(total?s.currentIndex/total*100:0)+'%';renderMastery(qn.masteryBefore??qn.word?.mastery??qn.word?.masteryScore??0,'before')}
function answer(){const r=document.querySelector('#answerArea input[type=radio]:checked');return r?r.value:($('answerInput')?.value||'')}
async function submit(){const a=answer();if(!String(a).trim()){$('feedbackArea').textContent='Please enter or select an answer.';return}try{const r=await DutchTrainerPractice.checkAnswer(a);if(!r.success){$('feedbackArea').textContent=r.reason==='empty-answer'?'Please enter or select an answer.':'Could not check this answer.';return}const f=r.feedback||{};const box=document.createElement('div');box.className=f.correct?'feedback correct':'feedback wrong';const h=document.createElement('strong');h.textContent=f.correct?'✓ Correct!':(f.almost?'~ Not quite':'✗ Not correct');const p=document.createElement('p');p.textContent=f.correct?(f.correctAnswer||'Good answer.'):(f.correctAnswer?`Correct answer: ${f.correctAnswer}`:'Please review this answer.');box.append(h,p);if(f.explanation){const e=document.createElement('p');e.textContent=f.explanation;box.appendChild(e)}$('feedbackArea').innerHTML='';$('feedbackArea').appendChild(box);renderMastery(f.mastery??r.mastery??0,'after');document.querySelectorAll('#answerArea input').forEach(i=>i.disabled=true);$('checkBtn').classList.add('hidden');$('nextBtn').classList.remove('hidden')}catch(e){console.error(e);$('feedbackArea').textContent='Could not check answer: '+e.message}}
async function start(opts){try{const r=await DutchTrainerPractice.startPractice(opts);if(!r.success){alert('No vocabulary available.');return}nav('practice');renderQuestion(r.question)}catch(e){console.error(e);alert('Could not start practice: '+e.message)}}
async function startQuick(){const type=await setting('practice.exerciseType','meaning'),count=Number(await setting('practice.questionCount',20)),words=await getSelectedVocabulary();await start({mode:'start',exerciseType:type,questionCount:count,vocabulary:words})}
async function startConfigured(){const type=$('exerciseType').value,n=Math.max(1,Number($('customQuestionCount').value)||Number(document.querySelector('.countPreset.active')?.dataset.value)||20),f=$('vocabularyFilter').value;let words=await getSelectedVocabulary();if(f==='new')words=await DutchTrainerSelection.selectNewVocabulary();else if(f==='weak')words=await DutchTrainerSelection.selectWeakVocabulary();else if(f==='due')words=await DutchTrainerSelection.selectDueVocabulary();else if(f==='pack'&&$('packSelector').value!=='all')words=await DutchTrainerSelection.selectVocabularyPack($('packSelector').value);$('practiceModal').classList.add('hidden');await start({exerciseType:type,questionCount:n,mode:'full',vocabulary:words})}
async function renderHistory(){const a=$('historyContent');if(!a)return;a.innerHTML='';const words=await getAllWords(),rows=[];words.forEach(w=>(w.history||w.answerHistory||w.practiceHistory||[]).forEach(h=>rows.push({date:h.answeredAt||h.timestamp||h.date,word:w.word||w.term||'',type:h.exerciseType||h.type||'',correct:h.correct,mastery:h.mastery})));rows.sort((x,y)=>new Date(y.date||0)-new Date(x.date||0));if(!rows.length){a.textContent='No practice history yet.';return}const t=document.createElement('table');t.innerHTML='<thead><tr><th>Date</th><th>Word</th><th>Exercise</th><th>Result</th><th>Mastery</th></tr></thead>';const b=document.createElement('tbody');rows.slice(0,200).forEach(r=>{const tr=document.createElement('tr');[r.date?new Date(r.date).toLocaleString():'',r.word,r.type,r.correct?'Correct':'Incorrect',`${Math.round(Number(r.mastery)||0)}%`].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td)});b.appendChild(tr)});t.appendChild(b);a.appendChild(t)}
function repeatPractice(){const last=window.__DutchTrainerLastPractice;if(!last){nav('home');return}start({exerciseType:last.exerciseType,questionCount:last.questionCount,mode:last.mode,vocabulary:last.vocabulary})}
function bind(){if(window.__DutchTrainerUIBound)return;window.__DutchTrainerUIBound=true;$('quickPracticeBtn')?.addEventListener('click',startQuick);$('practiceSetupBtn')?.addEventListener('click',async()=>{$('practiceModal').classList.remove('hidden');await loadPacks();await populateDefaults()});$('closePracticeModal')?.addEventListener('click',()=>$('practiceModal').classList.add('hidden'));$('dashboardBtn')?.addEventListener('click',()=>nav('dashboard'));$('packsBtn')?.addEventListener('click',()=>nav('packs'));$('settingsBtn')?.addEventListener('click',()=>nav('settings'));$('historyBtn')?.addEventListener('click',()=>nav('history'));$('saveSettingsBtn')?.addEventListener('click',saveSettings);$('settingsTheme')?.addEventListener('change',e=>applyTheme(e.target.value));$('importPackBtn')?.addEventListener('click',importPack);$('startPracticeBtn')?.addEventListener('click',startConfigured);document.querySelectorAll('.backBtn').forEach(b=>b.addEventListener('click',goBack));document.querySelectorAll('.countPreset').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.countPreset').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('customQuestionCount').value=''}));$('checkBtn')?.addEventListener('click',submit);$('nextBtn')?.addEventListener('click',()=>{const r=DutchTrainerPractice.nextQuestion();if(r.completed){nav('complete');$('sessionScore').textContent=`${r.state.correctCount} / ${r.state.answerCount} correct`}else renderQuestion(r.question)});$('exitPracticeBtn')?.addEventListener('click',goBack);$('backDashboardBtn')?.addEventListener('click',()=>nav('dashboard'));$('practiceAgainBtn')?.addEventListener('click',repeatPractice);document.addEventListener('keydown',e=>{if(!$('practiceScreen')?.classList.contains('active')||e.key!=='Enter')return;e.preventDefault();const s=DutchTrainerPractice.getState();if(s.answered)$('nextBtn')?.click();else $('checkBtn')?.click()})}
window.navigateTo=nav;window.renderPracticeQuestion=renderQuestion;window.initializeUI=bind;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();})();