```javascript
/* Dutch Vocabulary Trainer V2.2.8 UI */
(function(){'use strict';
const $=id=>document.getElementById(id);const text=v=>v&&typeof v==='object'?String(v.text??v.label??v.value??v.answer??'').trim():String(v??'').trim();
const viewMap={home:'homeScreen',dashboard:'dashboardScreen',packs:'packsScreen',settings:'settingsScreen',practice:'practiceScreen',complete:'completeScreen',history:'historyScreen'};
async function setting(k,f){try{return typeof getPracticeSettings==='function'&&k.startsWith('practice.')?(getPracticeSettings()[k.slice(9)]??f):await getSetting(k,f)}catch(_){return f}}
async function saveSetting(k,v){try{return await setSetting(k,v)}catch(e){console.warn(e);return false}}
function nav(name,push=true){const target=viewMap[name]||name;document.querySelectorAll('.screen').forEach(e=>e.classList.remove('active'));$(target)?.classList.add('active');if(push){try{history.pushState({view:name},'',name==='home'?location.pathname+location.search:`#${name}`)}catch(_){}}if(name==='dashboard')window.DutchTrainerDashboard?.render?.();if(name==='packs')window.DutchTrainerPacksUI?.refresh?.();if(name==='settings')loadSettings();if(name==='history')renderHistory()}
function goHome(){nav('home')}window.addEventListener('popstate',e=>nav(e.state?.view||'home',false));function ensureHistoryRoot(){try{if(!history.state?.view)history.replaceState({view:'home'},'',location.href)}catch(_){} }
async function loadSettings(){$('settingsExerciseType').value=await setting('practice.exerciseType','meaning');$('settingsQuestionCount').value=await setting('practice.questionCount',20);const t=await setting('ui.theme','system');$('settingsTheme').value=t;applyTheme(t)}
function applyTheme(t){const root=document.documentElement;if(t==='dark'){root.dataset.theme='dark';root.style.colorScheme='dark'}else if(t==='light'){root.dataset.theme='light';root.style.colorScheme='light'}else{root.dataset.theme='system';root.style.colorScheme=window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light'}}
async function saveSettings(){const type=$('settingsExerciseType').value,n=Math.max(1,Math.min(500,Number($('settingsQuestionCount').value)||20)),theme=$('settingsTheme').value;await saveSetting('practice.exerciseType',type);await saveSetting('practice.questionCount',n);await saveSetting('ui.theme',theme);if(typeof savePracticeSettings==='function')savePracticeSettings({exerciseType:type,questionCount:n});applyTheme(theme);$('settingsStatus').textContent=`Saved: ${type}, ${n} questions.`;await populateDefaults()}
function packWordsFor(p,all){return all.filter(w=>String(w.packId||'')===String(p.packId))}
function packStats(p,words){const ws=packWordsFor(p,words),scores=ws.map(w=>Number(w.mastery??w.masteryScore??w.score??0)).filter(Number.isFinite),avg=ws.length?Math.round(scores.reduce((a,b)=>a+b,0)/ws.length):0;return{total:ws.length,learned:ws.filter(w=>Number(w.mastery??w.masteryScore??w.score??0)>=90).length,due:ws.filter(w=>w.isDue||(w.dueAt&&new Date(w.dueAt)<=new Date())).length,weak:ws.filter(w=>Number(w.mastery??w.masteryScore??w.score??0)<40).length,pct:avg}}
function renderPack(p,words){const d=document.createElement('div');d.className='card pack-card';const top=document.createElement('div');top.className='pack-header';const title=document.createElement('strong');title.textContent=p.name;const show=document.createElement('button');show.className='secondary';show.textContent='Show';top.append(title,show);d.append(top);const stats=packStats(p,words);const pw=document.createElement('div');pw.className='progress-wrapper';const bar=document.createElement('div');bar.className='progress-bar';const fill=document.createElement('div');fill.className='progress-fill';fill.style.width=stats.pct+'%';bar.append(fill);const pct=document.createElement('span');pct.textContent=stats.pct+'%';pw.append(bar,pct);d.append(pw);const summary=document.createElement('p');summary.className='pack-stats-text';summary.textContent=`${stats.total} Total · ${stats.learned} Learned · ${stats.due} Due · ${stats.weak} Weak`;d.append(summary);const details=document.createElement('div');details.className='pack-details hidden';const list=document.createElement('div');list.className='pack-word-list';packWordsFor(p,words).forEach(w=>{const row=document.createElement('div');row.className='pack-word-row';const nl=document.createElement('strong');nl.textContent=w.dutch||w.word||w.term||'';const en=document.createElement('span');en.textContent=w.english||w.meaning||'';row.append(nl,en);list.append(row)});details.append(list);d.append(details);show.addEventListener('click',()=>{const open=!details.classList.contains('hidden');details.classList.toggle('hidden',open);show.textContent=open?'Show':'Hide'});return d}
async function loadPacks(){try{const ps=await DutchTrainerPacks.getAllPacks(),all=typeof getAllWords==='function'?await getAllWords():[],list=$('packsList'),sel=$('packSelector'),active=$('activePackSelector');if(sel){sel.innerHTML='<option value="all">All Packs</option>';ps.forEach(p=>{const o=document.createElement('option');o.value=p.packId;o.textContent=p.name;sel.append(o)})}if(active){active.innerHTML='<option value="all">All Vocabulary</option>';ps.forEach(p=>{const o=document.createElement('option');o.value=p.packId;o.textContent=p.name;active.append(o)});const s=typeof getVocabularySelection==='function'?getVocabularySelection():{};active.value=s.source==='pack'&&s.packId?s.packId:'all'}if(list){list.innerHTML='';if(!ps.length)list.textContent='No vocabulary packs installed.';else ps.forEach(p=>list.append(renderPack(p,all)))}}catch(e){console.error(e);if($('packsList'))$('packsList').textContent='Could not load Word Packs: '+e.message}}
async function setActivePack(){const id=$('activePackSelector')?.value;if(typeof selectAllVocabulary!=='function'||typeof selectVocabularyPack!=='function')return;if(id&&id!=='all')await selectVocabularyPack(id);else await selectAllVocabulary();if(typeof getAllWords==='function')window.DutchTrainerV2VocabularyPool=await getAllWords();await window.DutchTrainerPacksUI?.refresh?.();if(window.DutchTrainerDashboard)await window.DutchTrainerDashboard.render()}
async function importPack(){const f=$('packFileInput')?.files?.[0];if(!f){$('importStatus').textContent='Please choose a JSON Word Pack first.';return}try{const name=$('packNameInput')?.value.trim()||'';const r=await DutchTrainerImport.importFile(f,{selectImportedPack:true,packName:name});$('importStatus').textContent=`Imported ${r.pack.name}: ${r.added} new, ${r.updated} updated, ${r.skipped} skipped.`;$('packFileInput').value='';$('packNameInput').value='';if(typeof getAllWords==='function')window.DutchTrainerV2VocabularyPool=await getAllWords();await loadPacks();if(r.pack?.packId&&$('activePackSelector'))$('activePackSelector').value=r.pack.packId;await setActivePack()}catch(e){console.error(e);$('importStatus').textContent='Import failed: '+e.message}}
async function populateDefaults(){const t=await setting('practice.exerciseType','meaning'),n=Number(await setting('practice.questionCount',20));if($('exerciseType'))$('exerciseType').value=t;if($('customQuestionCount'))$('customQuestionCount').value='';document.querySelectorAll('.countPreset').forEach(b=>b.classList.toggle('active',Number(b.dataset.value)===n))}
function renderMastery(value,label){$('masteryArea')?.remove();const d=document.createElement('div');d.id='masteryArea';d.className='mastery-display';d.textContent=`Mastery ${label}: ${Math.round(Number(value)||0)}%`;$('questionCard')?.insertBefore(d,$('answerArea'))}
function renderQuestion(qn){if(!qn)return;const e=qn.exercise||{},type=String(qn.type||e.type||'meaning').toLowerCase();$('exerciseBadge').textContent=e.label||({meaning:'Meaning',recall:'Recall',fill:'Fill Sentence',choose:'Choose Word',production:'Production'}[type]||type);$('questionPrompt').textContent=e.prompt||'Answer the question.';$('questionContext').textContent=type==='meaning'?(e.dutchWord||qn.word?.dutch||''):type==='recall'?(e.meaning||qn.word?.english||''):(e.sentence||e.example||e.context||'');const area=$('answerArea');area.innerHTML='';if(type==='meaning'||type==='choose'||e.inputType==='choice'){(Array.isArray(e.options)?e.options:[]).forEach(o=>{const s=text(o);if(!s)return;const l=document.createElement('label'),r=document.createElement('input');l.className='practice-option';r.type='radio';r.name='practiceChoice';r.value=s;l.append(r,document.createTextNode(' '+s));area.append(l)});if(!area.children.length){const p=document.createElement('p');p.textContent='No choices available.';area.append(p)}}else{const i=document.createElement('input');i.id='answerInput';i.type='text';i.autocomplete='off';i.placeholder=type==='fill'?'Type the missing word':'Type your answer';area.append(i);setTimeout(()=>i.focus(),0)}$('feedbackArea').innerHTML='';$('checkBtn').classList.remove('hidden');$('nextBtn').classList.add('hidden');const s=DutchTrainerPractice.getState(),total=s.questions?.length||0;$('sessionCounter').textContent=`${s.currentIndex+1}/${total}`;renderMastery(qn.word?.mastery??qn.word?.masteryScore??0,'before')}
function answer(){const r=document.querySelector('#answerArea input[type=radio]:checked');return r?r.value:($('answerInput')?.value||'')}
async function submit(){const a=answer();if(!String(a).trim()){$('feedbackArea').textContent='Please enter or select an answer.';return}try{const r=await DutchTrainerPractice.checkAnswer(a);if(!r.success){$('feedbackArea').textContent='Could not check this answer.';return}const f=r.feedback||{};$('feedbackArea').innerHTML='';const box=document.createElement('div');box.className=f.correct?'feedback correct':'feedback wrong';const h=document.createElement('strong');h.textContent=f.correct?'✓ Correct!':(f.almost?'~ Not quite':'✗ Not correct');const p=document.createElement('p');p.textContent=f.correct?(f.correctAnswer||'Good answer.'):(f.correctAnswer?`Correct answer: ${f.correctAnswer}`:'Please review this answer.');box.append(h,p);$('feedbackArea').appendChild(box);renderMastery(f.mastery??r.mastery??0,'after');document.querySelectorAll('#answerArea input').forEach(i=>i.disabled=true);$('checkBtn').classList.add('hidden');$('nextBtn').classList.remove('hidden')}catch(e){console.error(e);$('feedbackArea').textContent='Could not check answer: '+e.message}}
async function renderHistory(){const a=$('historyContent');if(!a)return;a.innerHTML='';let rows=[];try{if(window.DutchTrainerHistory?.getSessions)rows=await window.DutchTrainerHistory.getSessions()}catch(e){console.warn('Could not load practice history:',e)}if(!Array.isArray(rows))rows=[];if(!rows.length){a.textContent='No practice history yet.';return}rows.sort((x,y)=>new Date(y.date||y.timestamp||y.answeredAt||0)-new Date(x.date||x.timestamp||x.answeredAt||0));const t=document.createElement('table');t.innerHTML='<thead><tr><th>Date</th><th>Word</th><th>Level</th><th>Exercise</th><th>Result</th><th>Mastery</th></tr></thead>';const b=document.createElement('tbody');rows.slice(0,200).forEach(r=>{const tr=document.createElement('tr'),result=r.result||r.outcome||(r.correct?'correct':'incorrect'),resultText=result==='almost'||result==='not_quite'||r.almost?'Not quite':result==='correct'?'Correct':'Not correct';[new Date(r.date||r.timestamp||r.answeredAt).toLocaleString(),r.word||r.dutch||'',r.level||'',r.type||r.exerciseType||'',resultText,`${Math.round(Number(r.masteryAfter??r.mastery??0))}%`].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});b.append(tr)});t.append(b);a.append(t)}
async function start(opts){try{if(typeof getAllWords==='function')window.DutchTrainerV2VocabularyPool=await getAllWords();const r=await DutchTrainerPractice.startPractice(opts);if(!r.success){alert('No vocabulary available.');return}window.__DutchTrainerLastPractice={exerciseType:r.state.exerciseType,questionCount:r.state.questionCount,mode:r.state.mode,vocabulary:r.state.selectedVocabulary};nav('practice');renderQuestion(r.question)}catch(e){console.error(e);alert('Could not start practice: '+e.message)}}
async function startQuick(){const ps=typeof getPracticeSettings==='function'?getPracticeSettings():{};const type=ps.exerciseType||await setting('practice.exerciseType','meaning'),count=Number(ps.questionCount||await setting('practice.questionCount',20)),words=await getSelectedVocabulary();await start({mode:'start',exerciseType:type,questionCount:count,vocabulary:words})}
async function startConfigured(){const type=$('exerciseType').value,n=Math.max(1,Number($('customQuestionCount').value)||Number(document.querySelector('.countPreset.active')?.dataset.value)||20),f=$('vocabularyFilter').value;let words;if(f==='all')words=await getSelectedVocabulary();else if(f==='pack'){const id=$('packSelector').value;words=await getSelectedVocabulary({source:id&&id!=='all'?'pack':'all',packId:id&&id!=='all'?id:null})}else words=await getSelectedVocabulary({source:f,packId:null,newOnly:f==='new',weakOnly:f==='weak',dueOnly:f==='due'});if(!Array.isArray(words)||!words.length){alert(`No words match the selected vocabulary filter: ${f}.`);return}$('practiceModal').classList.add('hidden');await start({exerciseType:type,questionCount:n,mode:'full',vocabulary:words})}
function repeatPractice(){const last=window.__DutchTrainerLastPractice;if(last)start({exerciseType:last.exerciseType,questionCount:last.questionCount,mode:last.mode,vocabulary:last.vocabulary});else nav('home')}
function bind(){if(window.__DutchTrainerUIBound)return;window.__DutchTrainerUIBound=true;ensureHistoryRoot();$('quickPracticeBtn')?.addEventListener('click',startQuick);$('practiceSetupBtn')?.addEventListener('click',async()=>{$('practiceModal').classList.remove('hidden');await loadPacks();await populateDefaults()});$('closePracticeModal')?.addEventListener('click',()=>$('practiceModal').classList.add('hidden'));$('dashboardBtn')?.addEventListener('click',()=>nav('dashboard'));$('packsBtn')?.addEventListener('click',()=>nav('packs'));$('settingsBtn')?.addEventListener('click',()=>nav('settings'));$('historyBtn')?.addEventListener('click',()=>nav('history'));$('saveSettingsBtn')?.addEventListener('click',saveSettings);$('settingsTheme')?.addEventListener('change',e=>applyTheme(e.target.value));$('importPackBtn')?.addEventListener('click',importPack);$('activePackSelector')?.addEventListener('change',setActivePack);$('startPracticeBtn')?.addEventListener('click',startConfigured);document.querySelectorAll('.backBtn').forEach(b=>b.addEventListener('click',goHome));document.querySelectorAll('.countPreset').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.countPreset').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('customQuestionCount').value=''}));$('checkBtn')?.addEventListener('click',submit);$('nextBtn')?.addEventListener('click',()=>{const r=DutchTrainerPractice.nextQuestion();if(r.completed){nav('complete');$('sessionScore').textContent=`${r.state.correctCount} / ${r.state.answerCount} correct`}else renderQuestion(r.question)});$('exitPracticeBtn')?.addEventListener('click',goHome);$('backDashboardBtn')?.addEventListener('click',()=>nav('dashboard'));$('practiceAgainBtn')?.addEventListener('click',repeatPractice);document.addEventListener('keydown',e=>{if(!$('practiceScreen')?.classList.contains('active')||e.key!=='Enter')return;e.preventDefault();const s=DutchTrainerPractice.getState();if(s.answered)$('nextBtn')?.click();else $('checkBtn')?.click()})}
window.navigateTo=nav;window.renderPracticeQuestion=renderQuestion;window.initializeUI=bind;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();})();
```
