/* Dutch Vocabulary Trainer V2.2.5 - Word Packs UI */
(function(){"use strict";
const $=id=>document.getElementById(id);
function addStyles(){if(document.getElementById("v225PackStyles"))return;const s=document.createElement("style");s.id="v225PackStyles";s.textContent=`
#packsScreen .v221-pack{display:block!important;text-align:left!important;box-sizing:border-box;width:100%;}
#packsScreen .v221-pack .pack-header{display:flex!important;justify-content:space-between!important;align-items:flex-start!important;width:100%!important;gap:16px;text-align:left!important;}
#packsScreen .v221-pack .pack-header>strong{display:block!important;text-align:left!important;flex:1 1 auto!important;min-width:0!important;}
#packsScreen .v221-pack .pack-actions{display:flex!important;gap:8px!important;flex:0 0 auto!important;}
#packsScreen .v221-pack .pack-progress{display:flex!important;align-items:center!important;gap:10px!important;width:100%!important;margin:8px 0!important;text-align:left!important;}
#packsScreen .v221-pack .pack-progress .progress-bar{flex:1 1 auto!important;}
#packsScreen .v221-pack .pack-stat-line{display:block!important;text-align:left!important;font-size:.9rem!important;opacity:.85;margin:4px 0 10px!important;width:100%!important;}
#packsScreen .v221-pack .pack-word-list{display:flex!important;flex-direction:column!important;gap:0!important;margin-top:12px!important;width:100%!important;max-height:420px!important;overflow:auto!important;text-align:left!important;}
#packsScreen .v221-pack .pack-word-row{display:grid!important;grid-template-columns:minmax(150px,1fr) minmax(180px,2fr)!important;gap:16px!important;width:100%!important;box-sizing:border-box!important;padding:6px 0!important;border-top:1px solid rgba(127,127,127,.2)!important;text-align:left!important;}
#packsScreen .v221-pack .pack-word-row>*{text-align:left!important;min-width:0!important;}
#packsScreen .v225-import-card{display:block!important;text-align:left!important;width:100%!important;box-sizing:border-box!important;}
#packsScreen .v225-import-layout{display:grid!important;grid-template-columns:minmax(0,1fr) 180px auto!important;align-items:center!important;gap:12px!important;width:100%!important;box-sizing:border-box!important;text-align:left!important;}
#packsScreen .v225-import-layout .file-field{display:block!important;justify-self:start!important;text-align:left!important;min-width:0!important;}
#packsScreen .v225-import-layout #packFileInput{display:block!important;margin:0!important;width:auto!important;max-width:100%!important;}
#packsScreen .v225-import-layout #packNameInput{display:block!important;justify-self:center!important;width:180px!important;min-width:180px!important;max-width:180px!important;box-sizing:border-box!important;margin:0!important;text-align:center!important;}
#packsScreen .v225-import-layout #importPackBtn{display:block!important;justify-self:end!important;margin:0!important;white-space:nowrap!important;}
#packsScreen .v225-import-status{display:block!important;width:100%!important;box-sizing:border-box!important;text-align:left!important;margin:12px 0 0!important;}
@media(max-width:700px){#packsScreen .v225-import-layout{grid-template-columns:1fr!important;}#packsScreen .v225-import-layout #packNameInput{justify-self:start!important;width:180px!important;min-width:180px!important;max-width:180px!important;}#packsScreen .v225-import-layout #importPackBtn{justify-self:end!important;}}
`;document.head.append(s)}
function packIdOf(pack){return String(pack?.packId??pack?.id??"");}
function wordPackId(word){return String(word?.packId??word?.pack?.packId??word?.pack?.id??"");}
function wordsFor(pack,words){const id=packIdOf(pack);return words.filter(w=>wordPackId(w)===id);}
function masteryValue(w){const candidates=[w?.mastery,w?.masteryScore,w?.score,w?.mastery?.score];for(const v of candidates){const n=Number(v);if(Number.isFinite(n))return Math.max(0,Math.min(100,n));}return 0;}
function dueValue(w){if(w?.isDue!==undefined)return Boolean(w.isDue);const v=w?.nextReview??w?.nextReviewAt??w?.dueAt??w?.dueDate;if(v===undefined||v===null||v==="")return false;const t=new Date(v).getTime();return Number.isFinite(t)&&t<=Date.now();}
function isNewValue(w){if(w?.isNew!==undefined)return Boolean(w.isNew);const a=Number(w?.stats?.attempts??0);return !Number.isFinite(a)||a===0;}
function weakValue(w){if(w?.isWeak!==undefined)return Boolean(w.isWeak);const m=masteryValue(w);return m>0&&m<40;}
function statData(pack,words){const ws=wordsFor(pack,words),total=ws.length,mastery=total?Math.round(ws.reduce((sum,w)=>sum+masteryValue(w),0)/total):0,learned=ws.filter(w=>masteryValue(w)>=90).length,due=ws.filter(dueValue).length,weak=ws.filter(weakValue).length,isNew=ws.filter(isNewValue).length;return{total,learned,due,weak,new:isNew,pct:mastery};}
function renderCompactPack(pack,words){const card=document.createElement("div");card.className="card pack-card v221-pack";const head=document.createElement("div");head.className="pack-header";const title=document.createElement("strong");title.textContent=pack.name||"Unnamed Pack";const buttons=document.createElement("div");buttons.className="pack-actions";const show=document.createElement("button");show.className="secondary";show.textContent="Show";const remove=document.createElement("button");remove.className="secondary danger";remove.textContent="Remove";buttons.append(show,remove);head.append(title,buttons);card.append(head);const st=statData(pack,words);const progress=document.createElement("div");progress.className="pack-progress";const bar=document.createElement("div");bar.className="progress-bar";const fill=document.createElement("div");fill.className="progress-fill";fill.style.width=st.pct+"%";bar.append(fill);const pct=document.createElement("span");pct.textContent=st.pct+"%";progress.append(bar,pct);card.append(progress);const stats=document.createElement("div");stats.className="pack-stat-line";stats.textContent=`${st.total} Total · ${st.learned} Learned · ${st.due} Due · ${st.weak} Weak`;card.append(stats);const details=document.createElement("div");details.className="pack-details hidden";const list=document.createElement("div");list.className="pack-word-list";wordsFor(pack,words).forEach(w=>{const row=document.createElement("div");row.className="pack-word-row";const nl=document.createElement("strong");nl.textContent=w.dutch||w.word||w.term||"";const en=document.createElement("span");en.textContent=w.english||w.meaning||"";row.append(nl,en);list.append(row)});details.append(list);card.append(details);show.addEventListener("click",()=>{const open=!details.classList.contains("hidden");details.classList.toggle("hidden",open);show.textContent=open?"Show":"Hide"});remove.addEventListener("click",async()=>{if(!window.confirm(`Remove the Word Pack "${pack.name}"?\n\nThis removes the pack and all its vocabulary. This cannot be undone.`))return;try{await DutchTrainerPacks.deletePack(packIdOf(pack));const active=$("activePackSelector");if(active&&active.value===packIdOf(pack)&&typeof selectAllVocabulary==="function")await selectAllVocabulary();await refreshPacks();if($("importStatus"))$("importStatus").textContent=`Removed ${pack.name}.`;}catch(e){console.error(e);if($("importStatus"))$("importStatus").textContent="Could not remove pack: "+e.message;}});return card;}
async function refreshPacks(){const packs=await DutchTrainerPacks.getAllPacks(),words=await getAllWords(),list=$("packsList");if(!list)return;list.innerHTML="";if(!packs.length){list.textContent="No vocabulary packs installed.";return}packs.forEach(p=>list.append(renderCompactPack(p,words)));const active=$("activePackSelector");if(active){const current=active.value;active.innerHTML='<option value="all">All Vocabulary</option>';packs.forEach(p=>{const o=document.createElement("option");o.value=packIdOf(p);o.textContent=p.name;active.append(o)});active.value=packs.some(p=>packIdOf(p)===current)?current:"all";}}
function installImportLayout(){const card=$("packNameInput")?.closest(".card"),file=$("packFileInput"),name=$("packNameInput"),btn=$("importPackBtn"),status=$("importStatus");if(!card||!file||!name||!btn)return;card.classList.add("v225-import-card");let wrap=card.querySelector(".v225-import-layout");if(!wrap){wrap=document.createElement("div");wrap.className="v225-import-layout";const field=document.createElement("div");field.className="file-field";field.append(file);wrap.append(field,name,btn);if(status)card.insertBefore(wrap,status);else card.append(wrap)}else{const field=wrap.querySelector(".file-field");if(field&&!field.contains(file))field.append(file);if(!wrap.contains(name))wrap.append(name);if(!wrap.contains(btn))wrap.append(btn)}if(status)status.classList.add("v225-import-status");}
async function handleImport(){const f=$("packFileInput")?.files?.[0];if(!f){$("importStatus").textContent="Please choose a JSON Word Pack first.";return}try{const name=$("packNameInput")?.value.trim()||"";const r=await DutchTrainerImport.importFile(f,{selectImportedPack:true,packName:name});$("importStatus").textContent=`Imported ${r.pack.name}: ${r.added} new, ${r.updated} updated, ${r.skipped} skipped.`;$("packFileInput").value="";$("packNameInput").value="";await refreshPacks();if(r.pack?.packId&&$("activePackSelector"))$("activePackSelector").value=r.pack.packId;if(typeof setActivePack==="function")await setActivePack()}catch(e){console.error(e);$("importStatus").textContent="Import failed: "+e.message}}
function install(){addStyles();installImportLayout();const importBtn=$("importPackBtn");if(importBtn&&!importBtn.dataset.v225Bound){importBtn.dataset.v225Bound="1";importBtn.addEventListener("click",handleImport)}const packsBtn=$("packsBtn");if(packsBtn&&!packsBtn.dataset.v225Refresh){packsBtn.dataset.v225Refresh="1";packsBtn.addEventListener("click",()=>setTimeout(refreshPacks,0))}refreshPacks().catch(console.error)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();window.DutchTrainerPacksUI={refresh:refreshPacks};})();