'use strict';

const DutchTrainer = window.DutchTrainer || (window.DutchTrainer = {});
const registry = {};
function register(name, exercise) { if (!name || !exercise || typeof exercise.generate !== 'function' || typeof exercise.check !== 'function') throw new Error(`Invalid exercise: ${name}`); registry[name] = Object.freeze({ name, ...exercise }); }
function get(name) { return registry[name] || null; }
function list() { return Object.keys(registry); }
function clean(value) { return String(value ?? '').trim(); }
function normalize(value) { return clean(value).toLocaleLowerCase('nl-NL'); }
function shuffle(values) { const r=[...values]; for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];} return r; }
function dutch(word) { return clean(word?.dutch || word?.word || word?.term || word?.lemma || ''); }
function english(word) { return clean(word?.english || word?.meaning || word?.translation || word?.definition || ''); }
function formStrings(value,out=[]){ if(typeof value==='string'){if(value.trim())out.push(value);return out;} if(Array.isArray(value)){value.forEach(v=>formStrings(v,out));return out;} if(value&&typeof value==='object')Object.values(value).forEach(v=>formStrings(v,out)); return out; }
function acceptedForms(word){const values=[dutch(word),word?.base,word?.lemma,...(Array.isArray(word?.variants)?word.variants:[]),...formStrings(word?.forms)];return[...new Set(values.map(clean).filter(Boolean))];}
function examples(word){const raw=[];for(const value of [word?.examples,word?.exampleSentences,word?.sentences,word?.example,word?.sentence]){if(Array.isArray(value))value.forEach(v=>raw.push(typeof v==='string'?v:(v?.nl||v?.sentence||v?.text||'')));else if(typeof value==='string')raw.push(value);else if(value&&typeof value==='object')raw.push(value.nl||value.sentence||value.text||'');}return[...new Set(raw.map(clean).filter(Boolean))];}
function escapeRegExp(value){return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function wordPattern(value){return value.trim().split(/\s+/).map(escapeRegExp).join('\\s+');}
function maskTarget(sentence,word){for(const target of acceptedForms(word).sort((a,b)=>b.length-a.length)){const re=new RegExp(`(^|[^\\p{L}])${wordPattern(target)}(?=$|[^\\p{L}])`,'iu');if(re.test(sentence))return sentence.replace(re,'$1_____');}return '';}
function sentenceWithGap(word){for(const sentence of examples(word)){const masked=maskTarget(sentence,word);if(masked&&masked!==sentence&&masked.includes('_____'))return masked;}return '';}
function uniqueOptions(answer,values){const seen=new Set([normalize(answer)]),result=[answer];for(const value of values){const text=clean(value),key=normalize(text);if(text&&!seen.has(key)&&result.length<4){seen.add(key);result.push(text);}}return shuffle(result);}
function distractors(vocabulary,word,mapper,answer){return(Array.isArray(vocabulary)?vocabulary:[]).filter(x=>x?.id!==word?.id).map(mapper).map(clean).filter(Boolean).filter(x=>normalize(x)!==normalize(answer));}
function levenshtein(a,b){const prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<cur.length;j++)prev[j]=cur[j];}return prev[b.length];}
function almostMatch(value,targets){const input=normalize(value);if(!input)return false;return targets.some(target=>{const expected=normalize(target),distance=levenshtein(input,expected),words=expected.split(/\s+/).filter(Boolean),limit=words.length===1?(expected.length<=5?1:expected.length<=9?2:3):(words.length<=2?1:2);return distance<=limit;});}
register('meaning',{label:'Meaning',generate(word,options=[],vocabulary=[]){const answer=dutch(word);const opts=Array.isArray(options)&&options.length?options:uniqueOptions(answer,distractors(vocabulary,word,dutch,answer));return{type:'meaning',prompt:'Choose the Dutch word that matches this English meaning.',context:english(word),answer,correctAnswer:answer,options:opts};},check(question,answer){return normalize(answer)===normalize(question.correctAnswer||question.answer);}});
register('recall',{label:'Recall',generate(word){const answer=english(word);return{type:'recall',prompt:'What is the English meaning of this Dutch word?',context:dutch(word),answer,correctAnswer:answer};},check(question,answer){return normalize(answer)===normalize(question.correctAnswer||question.answer);}});
register('fill',{label:'Fill Sentence',generate(word){const answer=dutch(word),sentence=sentenceWithGap(word);return{type:'fill',prompt:'Fill in the sentence with the appropriate Dutch word.',context:sentence||'No suitable sentence is available for this word.',answer,correctAnswer:answer,acceptedAnswers:acceptedForms(word)};},check(question,answer){const targets=question.acceptedAnswers||[question.correctAnswer||question.answer],value=clean(answer);if(targets.some(target=>normalize(target)===normalize(value)))return{correct:true,almost:false};return{correct:false,almost:almostMatch(value,targets)};}});
register('choose',{label:'Choose Word',generate(word,options=[],vocabulary=[]){const answer=dutch(word),sentence=sentenceWithGap(word),opts=Array.isArray(options)&&options.length?options:uniqueOptions(answer,distractors(vocabulary,word,dutch,answer));return{type:'choose',prompt:'Choose the Dutch word that completes the sentence.',context:sentence||'No suitable sentence is available for this word.',answer,correctAnswer:answer,options:opts};},check(question,answer){return normalize(answer)===normalize(question.correctAnswer||question.answer);}});
register('production',{label:'Production',generate(word){const answer=dutch(word);return{type:'production',prompt:'Write a natural Dutch sentence using this word.',context:answer,answer,correctAnswer:answer,acceptedAnswers:acceptedForms(word)};},check(question,answer){const value=normalize(answer),targets=question.acceptedAnswers||[question.correctAnswer||question.answer];return!!value&&value.length>normalize(question.correctAnswer||question.answer).length&&targets.some(target=>value.includes(normalize(target)));}});
DutchTrainer.exercises={register,get,list,create(word,name,vocabulary=[]){const type=String(name||'meaning').trim().toLowerCase(),exercise=get(type);if(!exercise)throw new Error(`Unknown exercise type: ${type}`);const generated=exercise.generate(word,[],vocabulary);return{...generated,type:generated.type||type,label:generated.label||exercise.label||type,correctAnswer:generated.correctAnswer??generated.answer??''};}};
